allowBuilds:
  esbuild: true
  sharp: false
minimumReleaseAgeExclude:
  - "@kieksme/csp-cli@0.6.1"
  - "@kieksme/csp-core@0.6.1"
  - "@kieksme/csp-plugin-chat@0.6.1"
  - "@kieksme/csp-plugin-contact@0.6.1"
  - "@kieksme/csp-plugin-content@0.6.1"
  - "@kieksme/csp-plugin-kuma@0.6.1"
  - "@kieksme/csp-plugin-signl4@0.6.1"
  - "@kieksme/csp-sdk@0.6.1"
patchedDependencies:
  "@kieksme/csp-cli@0.6.1": patches/@kieksme__csp-cli@0.6.1.patch
  "@kieksme/csp-core@0.6.1": patches/@kieksme__csp-core@0.6.1.patch
  '@kieksme/csp-plugin-chat@0.6.1': patches/@kieksme__csp-plugin-chat@0.6.1.patch
  "@kieksme/csp-plugin-signl4@0.6.1": patches/@kieksme__csp-plugin-signl4@0.6.1.patch
  '@kieksme/csp-sdk@0.6.1': patches/@kieksme__csp-sdk@0.6.1.patch
