allowBuilds:
  esbuild: true
  sharp: false
minimumReleaseAgeExclude:
  - '@kieksme/csp-cli@0.3.0'
  - '@kieksme/csp-core@0.3.0'
  - '@kieksme/csp-plugin-chat@0.3.0'
  - '@kieksme/csp-plugin-contact@0.3.0'
  - '@kieksme/csp-plugin-content@0.3.0'
  - '@kieksme/csp-plugin-kuma@0.3.0'
  - '@kieksme/csp-plugin-signl4@0.3.0'
  - '@kieksme/csp-sdk@0.3.0'
